### ISSUE TITLE
Use alternative module to `request`

### ISSUE THREAD

**Issue by mdb** [vinyldns/vinyldns-js#30]
The [request](https://github.com/request/request/issues/3142) Node.js module is going into maintenance mode. It would probably prove beneficial to leverage a different, more actively maintained module.

**Comment by pungggi** [comment]
hi there is already an issue for that see https://github.com/request/request/issues/3143

**Comment by mdb** [comment]
@pungggi I believe you've misunderstood. This is an issue to utilize a `request`-alternative library within `vinyldns-js`.
