### ISSUE TITLE
Support "get zone by name" and "get zone by ID" endpoints

### ISSUE THREAD

**Issue by mdb** [vinyldns/vinyldns-js#35]
`vinyldns-js`'s `getZone` method currently expects an `id`. However, given that VinylDNS now supports the following, it may be worth creating `getZoneByName` and `getZoneByID` methods, or changing `getZone` to do something like accept a `{name || id: 'foo'}`:

* https://www.vinyldns.io/api/get-zone-by-name.html
* https://www.vinyldns.io/api/get-zone-by-id.html

**Comment by nimaeskandary** [comment]
I recently prd this without seeing the card. Let me know if the getZone(id) and getZoneByName(name) is good enough or we should rename getZone to getZoneByID

**Comment by mdb** [comment]
Thanks @nimaeskandary ! I'm actually having second thoughts about the need for `getZoneByID` given that we already have a `getZone(id)` method. I'm going to close this issue but we can re-open if you or others feel differently.
